# Generated by Django 3.1.7 on 2021-04-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('schoolid', models.CharField(default='540000000000', max_length=20)),
                ('schoolpassword', models.CharField(default='zzuli000000', max_length=256)),
                ('mobile', models.CharField(default='16666666666', max_length=20)),
                ('homemobile', models.CharField(default='16666666666', max_length=20)),
                ('region', models.CharField(default='东风校区', max_length=20)),
                ('area', models.CharField(default='二区', max_length=20)),
                ('build', models.CharField(default='5号楼', max_length=20)),
                ('dorm', models.CharField(default='200', max_length=20)),
                ('schoolgps', models.CharField(default='河南省郑州市金水区郑州轻工业大学第二学生园区', max_length=20)),
                ('schoollat', models.CharField(default='34.48000', max_length=20)),
                ('schoollon', models.CharField(default='113.39190', max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
